export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const SET_PRODUCT_CATEGORY = "SET_PRODUCT_CATEGORY";
export const SET_PRODUCT_BY_CATEGORY = "SET_PRODUCT_BY_CATEGORY";
export const SET_HOMEPAGE_PRODUCTS = "SET_HOMEPAGE_PRODUCTS";
export const SET_PARTICULAR_PRODUCT = "SET_PARTICULAR_PRODUCT";
