export default {
  getProductCategory: "product-categories",
  getProductByCategory: "get-product-by-category",
  onLogin: "login",
  onRegister: "register",
  getHomePageProducts: "show-home-product",
  getProduct: "products",
  getProductById: "products",
  cart: "cart",
  order: "order",
  getPages: "get-pages",
  getCountry: "countries-list",
  getState: "states-list",
  getCity: "cities-list",
  getShippingCharges: "selling-zone-with-charge",
  getOrdersList: "order",
  updateUserDetails: "user-details",
  getAccountDetails: "get-account-detail",
  uploadProfilePicture: "upload-profile-picture",
  getUserDetails: "get-account-detail",
  getFiltersDetails: "filter-data",
  getWishList: "get-wishlist",
};
